export const CANONICAL_FIELDS = [
  "RODataPreparationID",
  "RepairOrderID",
  "CustomerProgramID",
  "RONumber",
  "SourceFeed",
  "OwnerFName",
  "OwnerLName",
  "OwnerAddress1",
  "OwnerAddress2",
  "OwnerCity",
  "OwnerStateProvince",
  "OwnerPostalZip",
  "OwnerCountryCode",
  "OwnerHomePhone",
  "OwnerWorkPhone",
  "OwnerCellPhone",
  "OwnerOtherPhone",
  "OwnerDayPhone",
  "OwnerNightPhone",
  "OwnerEmail",
  "VehicleYear",
  "VehicleMake",
  "VehicleModel",
  "InsuranceCompany",
  "ReferralSourceName",
  "EstimatorName",
  "InsuranceAgentName",
  "BUName",
  "BusinessKeyPSG",
  "TotalLaborHrs",
  "GrossAmount",
  "ClaimType",
  "VehicleArrivedDate",
  "RepairStartedDate",
  "DeliveredDate",
  "PaintTechFullName",
  "BodyTechFullName",
] as const;

export const CANONICAL_TO_FM_MAP: Record<string, string> = {
  RONumber: "R_RONumber",
  OwnerFName: "R_Customer_First",
  OwnerLName: "R_Customer_Last",
  OwnerCompanyName: "R_Customer_Company",
  OwnerAddress1: "R_Address",
  OwnerAddress2: "R_AddressB",
  OwnerCity: "R_Customer_City",
  OwnerStateProvince: "R_Customer_State",
  OwnerPostalZip: "R_Customer_Zip",
  OwnerEmail: "R_EmailAdress",
  OwnerCellPhone: "R_Phone_Home",
  OwnerWorkPhone: "R_Phone_Work",
  OwnerHomePhone: "R_Phone_Home2",
  OwnerOtherPhone: "R_Phone_Other",
  OwnerDayPhone: "R_Phone_Day",
  VehicleYear: "R_Vehicle_Year",
  VehicleMake: "R_Vehicle_Make",
  VehicleModel: "R_Vehicle_Model",
  InsuranceCompany: "R_InsuranceCompany",
  ReferralSourceName: "R_ReferedBy",
  EstimatorName: "R_Employee_Estimator",
  InsuranceAgentName: "R_Agent_Name",
  BUName: "R_Shop_Name",
  BusinessKeyPSG: "R_ShopID",
  GrossAmount: "R_RepairTotal",
  ClaimType: "R_PaymentType",
  VehicleArrivedDate: "R_Repair_In",
  DeliveredDate: "R_Repair_Out",
  BodyTechFullName: "R_Employee_Body",
  PaintTechFullName: "R_Employee_Paint",
};
