-- Persisted, freshness-gated weekly repair-demand forecasts.
-- Rollback: drop function public.run_collision_weekly_forecasts(date), then table public.collision_demand_forecasts.

create table public.collision_demand_forecasts (
  id bigint generated by default as identity primary key,
  company_id uuid not null references public.companies(id) on delete cascade,
  shop_id uuid not null references public.shops(id) on delete cascade,
  company_name text not null,
  forecast_week date not null,
  model_key text not null default 'trailing4_v1',
  predicted_repair_orders numeric(8,2),
  lower_repair_orders integer,
  upper_repair_orders integer,
  prediction_interval_pct integer not null default 80,
  source_latest_arrival_date date,
  source_age_days integer,
  status text not null,
  status_reason text not null,
  actual_repair_orders integer,
  absolute_error numeric(8,2),
  observed_at timestamptz,
  generated_at timestamptz not null default now(),
  unique (company_id, forecast_week, model_key),
  check (extract(isodow from forecast_week) = 1),
  check (status in ('published', 'stale_source', 'insufficient_history')),
  check (predicted_repair_orders is null or predicted_repair_orders >= 0),
  check (lower_repair_orders is null or lower_repair_orders >= 0),
  check (upper_repair_orders is null or upper_repair_orders >= lower_repair_orders),
  check (actual_repair_orders is null or actual_repair_orders >= 0),
  check (source_age_days is null or source_age_days >= 0)
);

create index collision_demand_forecasts_shop_week_idx
  on public.collision_demand_forecasts (shop_id, forecast_week desc);

alter table public.collision_demand_forecasts enable row level security;

comment on table public.collision_demand_forecasts is
  'Service-only weekly shop-demand forecasts. Non-published rows have null predictions and explain stale or insufficient input data.';

revoke all on public.collision_demand_forecasts from anon, authenticated;
grant select, insert, update on public.collision_demand_forecasts to service_role;
grant usage, select on sequence public.collision_demand_forecasts_id_seq to service_role;

create or replace function public.run_collision_weekly_forecasts(
  p_as_of_date date default current_date
)
returns jsonb
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_forecast_week date := pg_catalog.date_trunc('week', p_as_of_date::timestamp)::date;
  v_candidate record;
  v_prediction numeric(8,2);
  v_history_weeks integer;
  v_source_age integer;
  v_status text;
  v_reason text;
  v_published integer := 0;
  v_stale integer := 0;
  v_insufficient integer := 0;
  v_observed integer := 0;
begin
  if p_as_of_date is null or p_as_of_date > current_date + 1 then
    raise exception 'Forecast as-of date must not be null or more than one day in the future';
  end if;

  update public.collision_demand_forecasts forecast
  set actual_repair_orders = pg_catalog.coalesce((
        select demand.repair_orders
        from public.v_collision_weekly_demand demand
        where demand.company_id = forecast.company_id
          and demand.week_start = forecast.forecast_week
      ), 0),
      absolute_error = pg_catalog.abs(
        pg_catalog.coalesce((
          select demand.repair_orders
          from public.v_collision_weekly_demand demand
          where demand.company_id = forecast.company_id
            and demand.week_start = forecast.forecast_week
        ), 0)::numeric - forecast.predicted_repair_orders
      ),
      observed_at = pg_catalog.now()
  where forecast.status = 'published'
    and forecast.forecast_week < v_forecast_week
    and forecast.actual_repair_orders is null;

  get diagnostics v_observed = row_count;

  for v_candidate in
    select
      orders.company_id,
      orders.shop_id,
      orders.company_name,
      max(orders.arrival_date) as latest_arrival_date
    from public.v_collision_repair_orders orders
    where orders.arrival_date is not null
    group by orders.company_id, orders.shop_id, orders.company_name
  loop
    select pg_catalog.round(pg_catalog.avg(history.repair_orders), 2), count(*)::integer
      into v_prediction, v_history_weeks
    from (
      select demand.repair_orders
      from public.v_collision_weekly_demand demand
      where demand.company_id = v_candidate.company_id
        and demand.week_start < v_forecast_week
      order by demand.week_start desc
      limit 4
    ) history;

    v_source_age := pg_catalog.greatest(0, p_as_of_date - v_candidate.latest_arrival_date);

    if v_history_weeks < 4 then
      v_status := 'insufficient_history';
      v_reason := 'At least four completed repair weeks are required.';
      v_prediction := null;
      v_insufficient := v_insufficient + 1;
    elsif v_source_age > 14 then
      v_status := 'stale_source';
      v_reason := pg_catalog.format(
        'Latest repair arrival is %s days old; live publication requires 14 days or less.',
        v_source_age
      );
      v_prediction := null;
      v_stale := v_stale + 1;
    else
      v_status := 'published';
      v_reason := 'Trailing four-week average with an empirical 80% interval calibrated on the 2024 pilot year.';
      v_published := v_published + 1;
    end if;

    insert into public.collision_demand_forecasts (
      company_id,
      shop_id,
      company_name,
      forecast_week,
      model_key,
      predicted_repair_orders,
      lower_repair_orders,
      upper_repair_orders,
      prediction_interval_pct,
      source_latest_arrival_date,
      source_age_days,
      status,
      status_reason,
      generated_at
    ) values (
      v_candidate.company_id,
      v_candidate.shop_id,
      v_candidate.company_name,
      v_forecast_week,
      'trailing4_v1',
      v_prediction,
      case when v_prediction is null then null else pg_catalog.greatest(0, pg_catalog.floor(v_prediction - 5)::integer) end,
      case when v_prediction is null then null else pg_catalog.ceil(v_prediction + 5)::integer end,
      80,
      v_candidate.latest_arrival_date,
      v_source_age,
      v_status,
      v_reason,
      pg_catalog.now()
    )
    on conflict (company_id, forecast_week, model_key) do update set
      shop_id = excluded.shop_id,
      company_name = excluded.company_name,
      predicted_repair_orders = excluded.predicted_repair_orders,
      lower_repair_orders = excluded.lower_repair_orders,
      upper_repair_orders = excluded.upper_repair_orders,
      prediction_interval_pct = excluded.prediction_interval_pct,
      source_latest_arrival_date = excluded.source_latest_arrival_date,
      source_age_days = excluded.source_age_days,
      status = excluded.status,
      status_reason = excluded.status_reason,
      generated_at = excluded.generated_at;
  end loop;

  return pg_catalog.jsonb_build_object(
    'forecast_week', v_forecast_week,
    'published', v_published,
    'stale_source', v_stale,
    'insufficient_history', v_insufficient,
    'observations_updated', v_observed
  );
end;
$$;

comment on function public.run_collision_weekly_forecasts(date) is
  'Scores the trailing-four-week model and publishes only when repair arrivals are no more than 14 days stale. Service role only.';

revoke execute on function public.run_collision_weekly_forecasts(date)
  from public, anon, authenticated;
grant execute on function public.run_collision_weekly_forecasts(date)
  to service_role;
